import {
  MdAcUnit,
  MdAddAPhoto,
  MdArrowBack,
  MdBolt,
  MdCalendarMonth,
  MdCall,
  MdCameraAlt,
  MdCheckCircle,
  MdCleaningServices,
  MdConfirmationNumber,
  MdElectricalServices,
  MdFaceRetouchingNatural,
  MdFavoriteBorder,
  MdFormatPaint,
  MdHandyman,
  MdHome,
  MdHouse,
  MdLocationOn,
  MdLocalOffer,
  MdLockOutline,
  MdPayment,
  MdPerson,
  MdPersonOutline,
  MdPhoneIphone,
  MdPlumbing,
  MdSchool,
  MdSearch,
  MdSettings,
  MdStar,
  MdSupportAgent,
  MdVerified,
  MdVerifiedUser,
  MdWorkOutline,
} from 'react-icons/md'
import { FaApple, FaGoogle } from 'react-icons/fa'

export const iconMap = {
  search: MdSearch,
  bolt: MdBolt,
  verified: MdVerifiedUser,
  cleaning: MdCleaningServices,
  truck: MdLocalOffer,
  paint: MdFormatPaint,
  electric: MdElectricalServices,
  plumbing: MdPlumbing,
  climate: MdAcUnit,
  school: MdSchool,
  house: MdHouse,
  tools: MdHandyman,
  style: MdFaceRetouchingNatural,
}

export const Icons = {
  AddPhoto: MdAddAPhoto,
  Apple: FaApple,
  ArrowBack: MdArrowBack,
  Calendar: MdCalendarMonth,
  Camera: MdCameraAlt,
  Call: MdCall,
  CheckCircle: MdCheckCircle,
  Confirmation: MdConfirmationNumber,
  Favorite: MdFavoriteBorder,
  Google: FaGoogle,
  Home: MdHome,
  Location: MdLocationOn,
  Lock: MdLockOutline,
  Offer: MdLocalOffer,
  Payment: MdPayment,
  Person: MdPerson,
  PersonOutline: MdPersonOutline,
  Phone: MdPhoneIphone,
  Search: MdSearch,
  Settings: MdSettings,
  Star: MdStar,
  Support: MdSupportAgent,
  Verified: MdVerified,
  Work: MdWorkOutline,
}
